name: software-carpentries-scikit-hep-tutorial
channels:
  - conda-forge
dependencies:
  - aiohttp
  - fastjet
  - fsspec-xrootd
  - jupyterlab
  - lz4
  - matplotlib
  - nb_conda_kernels
  - nlopt
  - numba
  - numpy
  - pandas
  - python
  - python-xxhash
  - scikit-hep
  - scikit-hep-testdata
  - xrootd
  - zfit
  - zstandard
