name: skhep-tutorial
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - uproot
  - awkward
  - awkward-pandas
  - scikit-hep-testdata
  - vector
  - xrootd
  - fsspec-xrootd
  - matplotlib
  - particle
  - requests
  - aiohttp
  - hist
  - zfit>=0.27.0
  - fastjet
